#!/usr/bin/env python3
"""
    Name: video_pi.py
    Author:
    Created: 08/01/24
    Purpose: Stream video to a Tkinter interface using Picamera2
    Description: This script demonstrates how to display a live video stream
    and still images from the Raspberry Pi camera
    using the PiCamera2 library and Tkinter.
NOTE: Part of this program was generated by ChatGPT
"""

# Raspberry Pi Buster
# sudo pip3 install pillow -U

import tkinter as tk
import tkinter.ttk as ttk
# Import Picamera2 for controlling the camera
from picamera2 import Picamera2
# Import PIL for image processing
from PIL import Image, ImageTk
# Import datetime for timestamping the saved images
from datetime import datetime
# Import threading for running capture in a separate thread
import threading
# Import time for timing FPS calculation
import time


class PiCameraApp:
    def __init__(self):
        self.window = tk.Tk()

        # Set window location at
        # 600x50 for pi, 350x50 for pi zero
        self.window.geometry("+600+50")

        # Call self.quit when window is closed
        self.window.protocol("WM_DELETE_WINDOW", self.quit)

        self.window.title("Video Pi")

        # Initialize the Picamera2 object
        self.picam2 = Picamera2()

        # Create a preview configuration for the camera
        self.config = self.picam2.create_preview_configuration()

        # Configure the camera with the preview configuration
        self.picam2.configure(self.config)

        # Event to control the streaming thread
        self.stream_event = threading.Event()
        self.capture_thread = None

        self.frame_count = 0  # Counter for the number of frames
        self.start_time = time.time()  # Start time for FPS calculation
        # Frame interval in milliseconds (for 30 FPS)
        self.frame_interval = 1000 / 30
        self.image = None  # Store the latest image

        self.create_widgets()
        self.window.mainloop()

# ---------------------- START VIDEO STREAM ------------------------------ #
    def start_stream(self):
        """Start the video stream"""
        if not self.stream_event.is_set():
            self.stream_event.set()  # Signal the thread to start
            self.lbl_status_bar.configure(text=" Video Stream Running . . .")
            self.btn_start_stop.configure(text="Stop Stream")
            self.picam2.start()  # Start the camera

            # Reset frame count and start time for FPS calculation
            self.frame_count = 0
            self.start_time = time.time()

            # Start the capture frames thread
            self.capture_thread = threading.Thread(target=self._capture_frames)
            self.capture_thread.daemon = True
            self.capture_thread.start()

            # Start the update image thread
            self.start_update_image_thread()

# ---------------------- STOP VIDEO STREAM ------------------------------- #
    def stop_stream(self):
        """Stop the video stream"""
        if self.stream_event.is_set():
            self.stream_event.clear()  # Signal the thread to stop
            self.btn_start_stop.configure(text="Start Stream")
            self.lbl_status_bar.configure(text=" Video Stream Stopped")
            self.picam2.stop()  # Stop the camera

            # Wait for the capture thread to finish
            if self.capture_thread and self.capture_thread.is_alive():
                self.capture_thread.join()

            # Reset the update thread flag so it can be restarted
            self.update_thread_started = False

        self.frame_count = 0  # Reset the frame count

# ------------------------ CAPTURE IMAGE ----------------------------------- #
    def capture_image(self):
        """
            Capture a still image in a separate thread,
              save it to the hard drive.
        """
        self.stop_stream()
        # Ensure that streaming is stopped before capturing an image
        if not self.stream_event.is_set():
            threading.Thread(target=self._capture_image_thread).start()
        self.start_stream()

# ------------------------ CAPTURE IMAGE THREAD ---------------------------- #
    def _capture_image_thread(self):
        """
            The actual method that captures the image
            and saves it to the hard drive.
            Runs in a separate thread to prevent blocking the main thread.
        """
        # Check again if streaming is stopped before capturing an image
        if not self.stream_event.is_set():
            if self.image is not None:
                # Convert the frame array to an image
                image = Image.fromarray(self.image)

                # Convert image to RGB mode if necessary
                if image.mode == 'RGBA':
                    image = image.convert('RGB')

                # Generate a timestamped filename for the image
                filename = datetime.now().strftime("%Y-%m-%d_%H-%M-%S") + ".jpg"
                # Save the image to the hard drive in JPEG format
                image.save(filename, 'JPEG')
                print(f"Image saved as {filename}")

# ------------------------ CAPTURE FRAMES ---------------------------------- #
    def _capture_frames(self):
        """Continuously capture frames from the camera in a separate thread"""
        while self.stream_event.is_set():
            # Capture a frame from the camera
            frame = self.picam2.capture_array()
            # Store the latest frame
            self.image = frame

            # Increment frame count
            self.frame_count += 1

            # Calculate elapsed time
            elapsed_time = time.time() - self.start_time

            # Update FPS every second
            if elapsed_time >= 1.0:
                fps = self.frame_count / elapsed_time
                self.lbl_status_bar.configure(
                    text=f" Video Stream Running . . . | FPS: {fps:.2f}"
                )
                # Reset frame count and start time
                self.frame_count = 0
                self.start_time = time.time()

            # Sleep to maintain frame interval
            time.sleep(self.frame_interval / 1000.0)

# ------------------------ UPDATE IMAGE ------------------------------------ #
    def update_image(self):
        """Update the Canvas widget with the latest image from the camera."""
        while self.stream_event.is_set():
            # Check if there is a frame to display
            if self.image is not None:
                # Convert frame array to an image that can be displayed in Tkinter
                image = Image.fromarray(self.image)
                image = ImageTk.PhotoImage(image)

                # Update the Canvas widget with the new image
                self.canvas.create_image(
                    0,            # x-coordinate for the image's top-left corner
                    0,            # y-coordinate for the image's top-left corner
                    anchor=tk.NW, # Anchor image at top-left corner (North-West)
                    image=image   # Image to be displayed
                )

                # Store the image as an attribute of the object
                # to prevent garbage collection
                self.photo = image

            # Sleep to maintain frame interval
            time.sleep(self.frame_interval / 1000.0)

# --------------------- START UPDATE IMAGE THREAD -------------------------- #
    def start_update_image_thread(self):
        """Start the update_image method in a separate thread."""
        if not hasattr(self, 'update_thread_started') or not self.update_thread_started:
            update_thread = threading.Thread(target=self.update_image)
            update_thread.daemon = True
            update_thread.start()
            self.update_thread_started = True

# ----------------------- START STOP VIDEO STREAM -------------------------- #
    def start_stop_stream(self):
        """Toggle the video stream on or off"""
        if self.stream_event.is_set():
            self.stop_stream()
        else:
            self.start_stream()

# ------------------ CREATE WIDGETS ---------------------------------------- #
    def create_widgets(self):
        # Constant to have all the buttons the same width
        BUTTON_WIDTH = 16

        # Create canvas to size and display image
        self.canvas = tk.Canvas(
            self.window,
            width=640,
            height=480
        )

        self.btn_start_stop = ttk.Button(
            self.window,
            text="Start Stream",
            command=self.start_stop_stream,
            width=BUTTON_WIDTH
        )

        self.btn_capture_image = ttk.Button(
            self.window,
            text="Capture Image",
            command=self.capture_image,
            width=BUTTON_WIDTH
        )

        self.btn_quit = ttk.Button(
            self.window,
            text="Quit",
            command=self.quit, width=BUTTON_WIDTH
        )

        message = f" Picamera2 Video Stream"
        self.lbl_status_bar = tk.Label(
            self.window, text=message, anchor=tk.W, relief=tk.RIDGE
        )

        self.canvas.grid(row=0, column=0, columnspan=4)

        self.btn_start_stop.grid(row=1, column=0)
        self.btn_capture_image.grid(row=1, column=2)
        self.btn_quit.grid(row=1, column=3)

        self.lbl_status_bar.grid(row=2, column=0, columnspan=4, sticky="WE")

        # Set padding for all widgets
        for child in self.window.winfo_children():
            child.grid_configure(padx=6, pady=6, ipadx=1, ipady=1)

        # The Escape key will activate the quit method
        self.window.bind('<Escape>', self.quit)

        # Handle window closing clean up camera resources
        self.window.protocol("WM_DELETE_WINDOW", quit)

# --------------------------- QUIT PROGRAM --------------------------------- #
    def quit(self, *args):
        self.stop_stream()  # Ensure the stream is stopped
        self.window.destroy()


def main():
    # Create an instance of the PiCameraApp class
    app = PiCameraApp()


if __name__ == "__main__":
    main()
